fix lint (#72)

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -21,13 +21,11 @@ if ! pnpm typecheck; then
     exit 1
 fi
 
-# Run lint TODO(sshader) restore
-echo "Skipping lint because Sarah wants to push up a branch"
-# echo "Running lint..."
-# if ! pnpm lint; then
-#     echo "❌ Linting failed! Run 'pnpm lint:fix' to fix the easy issues."
-#     echo "Once you're done, don't forget to add your beautification to the commit! 🤩"
-#     exit 1
-# fi
+echo "Running lint..."
+if ! pnpm lint; then
+    echo "❌ Linting failed! Run 'pnpm lint:fix' to fix the easy issues."
+    echo "Once you're done, don't forget to add your beautification to the commit! 🤩"
+    exit 1
+fi
 
 echo "👍 All checks passed! Committing changes..."
